#!/usr/bin/env bash
# Re-vendor Miking's numerics dependencies into lib/.
#
# Everything under lib/{stan-math,boost,eigen}/ and lib/overlay/ is generated
# by this script. Do not hand-edit those trees: change vendor-root.cpp (to
# reach a new header) or the PRUNE table below (to cut an unwanted backend
# edge), then re-run. Keeping the patches as rules rather than as frozen
# copies is what makes the next upstream bump a re-run instead of a merge.
#
# Requires: git, g++, and network access. Takes a couple of minutes, almost
# all of it cloning Stan Math.
set -euo pipefail

# Stan Math vendors mutually-tested Boost and Eigen in its own lib/, so one
# pinned tag fixes all three. Bump this and re-run; check the versions the
# script prints afterwards.
STAN_TAG=v5.3.0

LIB=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT

# Umbrella headers that unconditionally pull a backend we do not use. Each
# entry is "<path under stan/>|<include substring to drop>". Nothing in Stan
# Math *calls* into either backend from prim/ -- these are include-only edges,
# which is why cutting them is safe. Verified for v5.3.0; if a bump adds a new
# edge the closure step below fails loudly with the missing header.
PRUNE=(
  "math/prim/core.hpp|init_threadpool_tbb"   # Intel TBB threadpool
  "math/prim/err.hpp|check_flag_sundials"    # SUNDIALS (CVODES/IDAS/KINSOL)
)

echo "==> cloning stan-math $STAN_TAG"
git clone --depth 1 --branch "$STAN_TAG" https://github.com/stan-dev/math.git \
  "$WORK/stan-math" 2>&1 | tail -1
SRC=$WORK/stan-math
BOOST_SRC=$(echo "$SRC"/lib/boost_*)
EIGEN_SRC=$(echo "$SRC"/lib/eigen_*)
echo "    boost: $(basename "$BOOST_SRC")"
echo "    eigen: $(basename "$EIGEN_SRC")"

echo "==> generating lib/overlay (pruned umbrella headers)"
rm -rf "$LIB/overlay"
for entry in "${PRUNE[@]}"; do
  rel=${entry%%|*}; drop=${entry##*|}
  mkdir -p "$LIB/overlay/stan/$(dirname "$rel")"
  {
    echo "// GENERATED by lib/vendor.sh from stan-math $STAN_TAG -- do not edit."
    echo "// Identical to upstream stan/$rel with the '$drop' include removed."
    grep -v "$drop" "$SRC/stan/$rel"
  } > "$LIB/overlay/stan/$rel"
  echo "    stan/$rel  (dropped $drop)"
done

echo "==> computing the header closure from vendor-root.cpp"
# The overlay must precede the upstream tree so the pruned copies win.
g++ -std=c++17 -pthread -M \
  -I"$LIB/overlay" -I"$SRC" -I"$BOOST_SRC" -I"$EIGEN_SRC" \
  "$LIB/vendor-root.cpp" 2>/dev/null \
  | tr ' \\' '\n\n' | grep -E '^/' | sort -u > "$WORK/closure.txt"
echo "    $(wc -l < "$WORK/closure.txt") headers reached (incl. system)"

echo "==> copying the closure into lib/"
copy_tree() { # <source root> <dest name>
  local root=$1 dest=$2 n=0
  rm -rf "$LIB/$dest"
  while read -r f; do
    local rel=${f#"$root"/}
    mkdir -p "$LIB/$dest/$(dirname "$rel")"
    cp "$f" "$LIB/$dest/$rel"
    n=$((n+1))
  done < <(grep "^$root/" "$WORK/closure.txt")
  local sz; sz=$(du -sh "$LIB/$dest" 2>/dev/null | cut -f1)
  printf '    %-12s %4d headers  %s\n' "$dest" "$n" "$sz"
}
copy_tree "$SRC"        stan-math
copy_tree "$BOOST_SRC"  boost
copy_tree "$EIGEN_SRC"  eigen

echo "==> collecting licenses"
rm -rf "$LIB/LICENSES"; mkdir -p "$LIB/LICENSES"
cp "$SRC/LICENSE.md"                "$LIB/LICENSES/stan-math.BSD-3-Clause.txt"
cp "$BOOST_SRC/LICENSE_1_0.txt"     "$LIB/LICENSES/boost.BSL-1.0.txt"
for f in COPYING.MPL2 COPYING.APACHE COPYING.BSD COPYING.MINPACK COPYING.README; do
  cp "$EIGEN_SRC/$f" "$LIB/LICENSES/eigen.$f.txt"
done
# NOTE: deliberately NOT copying stan-math's own licenses/ directory. At
# v5.3.0 it still ships LGPL v3 text as eigen-license.txt and a
# dependencies.txt naming eigen 3.3.3 / boost 1.69.0 / TBB 2019_U5, none of
# which match what the repo actually vendors. See README.md.
echo "    $(ls "$LIB/LICENSES" | wc -l) files"

echo "==> recording provenance"
cat > "$LIB/VENDORED.txt" <<EOF
Generated by lib/vendor.sh -- do not edit.

stan-math  $STAN_TAG  $(git -C "$SRC" rev-parse HEAD)
boost      $(basename "$BOOST_SRC" | sed 's/boost_//')  (as vendored by stan-math $STAN_TAG)
eigen      $(basename "$EIGEN_SRC" | sed 's/eigen_//')  (as vendored by stan-math $STAN_TAG)

closure root : lib/vendor-root.cpp
pruned edges : $(printf '%s ' "${PRUNE[@]}")
EOF
cat "$LIB/VENDORED.txt"

echo "==> gate: does vendor-root.cpp compile against lib/ alone?"
# No -I outside lib/, so a missed header fails here rather than in CI.
#
# -DEIGEN_MPL2_ONLY is a license gate, not an optimisation. Eigen 3.4.x is
# "primarily MPL2" but does contain some LGPL-licensed code, and this macro
# makes Eigen itself raise a compile error if any of it is reached. Building
# with it always on turns "we only ship MPL2-or-more-permissive Eigen" from a
# claim someone has to audit into something the compiler proves on every
# build. Keep it in the shim's flags too (lib/mi-stats), not just here.
if g++ -std=c++17 -O2 -pthread -DEIGEN_MPL2_ONLY \
     -I"$LIB/overlay" -I"$LIB/stan-math" -I"$LIB/boost" -I"$LIB/eigen" \
     -fsyntax-only "$LIB/vendor-root.cpp"; then
  echo "    OK -- self-contained, and MPL2-or-more-permissive only"
else
  echo "    FAILED -- either the closure is incomplete or LGPL Eigen code is" >&2
  echo "    reachable; see the error above" >&2
  exit 1
fi
