// GENERATED by lib/vendor.sh from stan-math v5.3.0 -- do not edit.
// Identical to upstream stan/math/prim/core.hpp with the 'init_threadpool_tbb' include removed.
#ifndef STAN_MATH_PRIM_CORE_HPP
#define STAN_MATH_PRIM_CORE_HPP

#include <stan/math/prim/core/operator_addition.hpp>
#include <stan/math/prim/core/operator_division.hpp>
#include <stan/math/prim/core/operator_equal_equal.hpp>
#include <stan/math/prim/core/operator_minus.hpp>
#include <stan/math/prim/core/operator_multiplication.hpp>
#include <stan/math/prim/core/operator_not_equal.hpp>
#include <stan/math/prim/core/operator_plus.hpp>
#include <stan/math/prim/core/operator_subtraction.hpp>

#endif
