#!/usr/bin/env fish

set STAN_VERSION v5.4.0

cd (status dirname)


# === Clone the stan-math repository ===

set -g workDir (mktemp --directory)
git clone https://github.com/stan-dev/math.git --depth 1 --branch $STAN_VERSION $workDir
or begin
    echo "Cloning stan failed, aborting."
    echo "Work directory '$workDir' left in place."
    exit 1
end

set stanDir $workDir/stan/
set eigenDir $workDir/lib/eigen_*/
set boostDir $workDir/lib/boost_*/


# === Remove some includes that we don't need ===

function pruneIncludes --argument-names file target
  sed --in-place '\@^#include <'(string escape --style regex -- $target)'>$@d' $workDir/$file
end

pruneIncludes stan/math/prim/core.hpp stan/math/prim/core/init_threadpool_tbb.hpp
pruneIncludes stan/math/prim/err.hpp stan/math/prim/err/check_flag_sundials.hpp


# === Generate the `.cpp` file that includes all others ===

rm -f root.cpp
echo "// This file is generated by vendor.fish, do not edit manually." >> root.cpp
echo "" >> root.cpp
printf '#include "%s"\n' ./cpp/*.cpp >> root.cpp


# === Figure out which files we need ===

set includes $workDir $eigenDir $boostDir

set -g dependencies (cpp -M -I$includes -DBOOST_MATH_STANDALONE root.cpp \
    | tail --lines=+2 \
    | string trim --chars ' \\' \
    | string split ' ')
or begin
    echo "Failed to process dependencies, aborting."
    echo "Work directory '$workDir' left in place."
    exit 1
end

# NOTE(vipa, 2026-09-29): Add dependencies we know are platform
# specific, and thus won't be detected by the automatic check above
set -a dependencies $boostDir/boost/config/{stdlib,platform,compiler}/*.hpp

function dependenciesIn --argument-names dir
    path resolve -- $dependencies | sort | uniq | rg '^'(string escape --style regex $dir) --replace ''
end


# === Clear old vendor, copy files we need ===

function copyDependencies --argument-names src dst
    dependenciesIn $src | rsync -a --files-from=- $src $dst
end

rm -rf vendor/{stan,eigen,boost}

copyDependencies $stanDir vendor/stan/
copyDependencies $eigenDir vendor/eigen/
copyDependencies $boostDir vendor/boost/


# === Copy licenses ===

function copyLicense --argument-names src dst
    cp $src $dst
    or begin
        echo "Failed to copy license from '$src'"
        echo "to '$dst', aborting."
        echo "Work directory '$workDir' left in place."
        exit 1
    end
end

rm -f licenses/*

copyLicense $workDir/LICENSE.md licenses/stan.LICENSE.md
copyLicense $boostDir/LICENSE_1_0.txt licenses/boost.LICENSE.txt
for f in COPYING.MPL2 COPYING.APACHE COPYING.BSD COPYING.MINPACK COPYING.README
  copyLicense $eigenDir/$f licenses/eigen.$f
end


# === Done, clear the work directory ===

rm -rf $workDir
